# Generated by Django 3.0.8 on 2020-07-16 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('endDate', models.DateTimeField()),
                ('picture', models.URLField()),
                ('description', models.CharField(max_length=6)),
                ('category', models.CharField(choices=[('HM', 'Home'), ('FS', 'Fashion'), ('TY', 'Toys'), ('EL', 'electronics'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=6)),
                ('time', models.DateTimeField(auto_now=True)),
                ('listing', models.ManyToManyField(blank=True, related_name='productComment', to='auctions.Listing')),
                ('user', models.ManyToManyField(blank=True, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('time', models.DateTimeField(auto_now=True)),
                ('listing', models.ManyToManyField(blank=True, related_name='productBid', to='auctions.Listing')),
                ('user', models.ManyToManyField(blank=True, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
