# Generated by Django 3.0.8 on 2020-07-17 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
