# Generated by Django 3.0.8 on 2020-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('HM', 'Home'), ('FS', 'Fashion'), ('TY', 'Toys'), ('EL', 'electronics'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
